CREATE TABLE admin(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE class_level(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE field(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE courses(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    level BIGINT UNSIGNED NULL DEFAULT NULL,
    field BIGINT UNSIGNED NULL DEFAULT NULL,

    FOREIGN KEY fk_courses_level(level) REFERENCES class_level(id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY fk_courses_field(field) REFERENCES field(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE programs(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE programs_content(
    program BIGINT UNSIGNED NOT NULL,
    course BIGINT UNSIGNED NOT NULL,

    CONSTRAINT pk_programs_content PRIMARY KEY (program,course),
    FOREIGN KEY fk_programs_content_program(program) REFERENCES programs(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY fk_programs_content_course(course) REFERENCES courses(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE class(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(100) DEFAULT NULL,
    program BIGINT UNSIGNED NOT NULL,
    level BIGINT UNSIGNED NULL,
    size INT NOT NULL DEFAULT 30,

    FOREIGN KEY fk_class_program(program) REFERENCES programs(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY fk_class_level(level) REFERENCES class_level(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE teachers(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(100),
    surname VARCHAR(100),
    field BIGINT UNSIGNED NULL DEFAULT NULL,

    FOREIGN KEY fk_teachers_field(field) REFERENCES field(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE students(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(100),
    surname VARCHAR(100),
    dateofbirth DATE NOT NULL,
    level BIGINT UNSIGNED NULL DEFAULT NULL,
    class BIGINT UNSIGNED NULL DEFAULT NULL,
    confirm TINYINT(1) NOT NULL DEFAULT 0,

    FOREIGN KEY fk_students_level(level) REFERENCES class_level(id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY fk_students_class(class) REFERENCES class(id) ON DELETE SET NULL ON UPDATE CASCADE
);


CREATE TABLE rooms(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    size INT NOT NULL DEFAULT 30
);

CREATE TABLE schedule(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    room BIGINT UNSIGNED NOT NULL,
    class BIGINT UNSIGNED NOT NULL,
    teacher BIGINT UNSIGNED NOT NULL,
    course BIGINT UNSIGNED NOT NULL,
    start DATETIME NOT NULL,
    end DATETIME NOT NULL,

    FOREIGN KEY fk_schedule_room(room) REFERENCES rooms(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY fk_schedule_class(class) REFERENCES class(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY fk_schedule_teacher(teacher) REFERENCES teachers(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY fk_schedule_course(course) REFERENCES courses(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE evaluations(
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    student BIGINT UNSIGNED NOT NULL,
    score INT DEFAULT 10 NOT NULL,
    
    FOREIGN KEY fk_evaluations_course(course) REFERENCES courses(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY fk_results_student(student) REFERENCES students(id) ON DELETE CASCADE ON UPDATE CASCADE
);
